"""add email to persons

Revision ID: 3a104b7d2819
Revises: a62d22a20b7b
Create Date: 2026-05-04 15:27:24.967615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a104b7d2819'
down_revision = 'a62d22a20b7b'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
