"""Migracion: Agregar is_active a Topics, Lessons y Activities

Revision ID: 671eda77e5e6
Revises: 7687be996e9d
Create Date: 2026-03-03 23:33:43.659512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671eda77e5e6'
down_revision = '7687be996e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('academic_lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('academic_topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_topics', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('academic_lessons', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('academic_activities', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
