"""Migracion: Agregar is_active a Group para Soft Delete

Revision ID: 7687be996e9d
Revises: fd5e672f2758
Create Date: 2026-03-03 22:39:25.767264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7687be996e9d'
down_revision = 'fd5e672f2758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_groups', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
