"""agregar is_active a roles, persons, enrollments y student_progress

Revision ID: 9f6c64d0700b
Revises: 671eda77e5e6
Create Date: 2026-03-04 21:18:59.187760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6c64d0700b'
down_revision = '671eda77e5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('academic_student_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('academic_student_progress', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('academic_enrollments', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
